### ISSUE TITLE
Travis CI: Add JDK test matrix, including failure cases

### ISSUE THREAD

**Issue by rickhull** [Glassdoor/planout4j#17]
http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail

Something like:
```
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
matrix:
  allow_failures:
    - jdk: oraclejdk8
```
